# Site settings
title: Mathematics of Deep Learning
email: zwimpee(at)gmail.com
description: ""
baseurl: ""
url: "http://zwimpee.github.io"
github_username: zwimpee
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge